### ISSUE TITLE
How to know the isVisible of a layer ?

### ISSUE THREAD

**Issue by magic1412kid** [TheCyberRonin/ase-parser#21]
When try to set layer's visible/hidden at aseprite, I observed that the "flags" attribute of Layer Object by ase-parser from 3 to 2. What mean the "flags" value ? Is there a reasonable way to know the layer's visible ? Please ..

**Comment by TheCyberRonin** [comment]
I just added a feature in version `v0.0.18` that will make what flags are set more clear. There is now a map of the flags and whether or not they are "on" or "off" instead of the raw flag value.

Sorry for taking so long to get to this, but this should be exactly what you need.

**Comment by magic1412kid** [comment]
> I just added a feature in version `v0.0.18` that will make what flags are set more clear. There is now a map of the flags and whether or not they are "on" or "off" instead of the raw flag value.
> 
> Sorry for taking so long to get to this, but this should be exactly what you need.

Thank you for providing this convenient library, it helps me develop games better !
